package itsolver.utils;

public enum NotificationType {
	PROJECT_CREATED,
	PROJECT_EDITED,
	INVITATION_TO_COLABORATE, 
	INVITATION_RECEIVED,
	INVITATION_ACEPTED, 
	COLLABORATION_DONE, 
	COMMENT_ON_PROJECT
}
